# ---------------- #
#   Main Configs   #
# ---------------- #
title: Zale - ZhangLe's Website
name: Zale
description: Zale's Personal Website
keywords: Zale, blog, ZhangLe

url:
baseurl:  "/"
domain:
permalink:     /articles/:year/:month/:title.html
paginate_path: 'page:num'
paginate:   10
source_code: https://github.com/zl810881283/zl810881283.github.io

timezone: Asia/Shanghai
encoding: "utf-8"

# ---------------- #
#      Author      #
# ---------------- #
organization: Chongqing University
organization_url: https://www.cqu.edu.cn
location: Chongqing, China
email: 810881283@qq.com
github_account: zl810881283
resumes:
  -
    lang: 中文简历
    link: /attachments/resumes/zhangle_resume_cn.pdf
    icon: cn
  -
    lang: English
    link:
    icon: gb
# ---------------- #
#      Jekyll      #
# ---------------- #
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

exclude: ["node_modules", "bower.json", "Gemfile", "Gemfile.lock", "gulpfile.js", "package.json"]
source:      .
destination: ./_site

quiet:    false
defaults: []

gems:
  - jemoji
  - rouge
  - jekyll-html-pipeline
  - jekyll-paginate

analytics:
  provider: baidu
  google:
    tracking_id: 'UA-76860417-1'
  baidu:
    tracking_id: 'f0c036c8faf0eda95f1daedde0f0a398'

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

#  -
#    href: /blog
#    label: Blog

  -
    href: /categories
    label: Categories

  -
    href: /wiki
    label: Wiki

  -
    href: /bookmark
    label: Bookmark

  -
    href: /open-source
    label: Open-Source

  -
    href: /about
    label: About

# ---------------- #
#       Wiki       #
# ---------------- #
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Socials     #
# ---------------- #
socials:
  -
    type: zhihu
    account: zl810881283
    home: https://www.zhihu.com/people/zl810881283
  -
    type: twitter
    account:
  -
    type: facebook
    account:

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo, changyan
# !!!Important!!! Please modify usernames below to yours
comments:
  provider: disqus
  disqus:
    username: zl810881283
    sitename: zale
  duoshuo:
    username:
  changyan:
    appid:
    conf:

# ---------------- #
#      Data        #
# ---------------- #
skill_software_keywords: [Java, C, C++, MySQL, Oracle, SQLite, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, JSP]
skill_web_keywords: [HTML, CSS, Javascript, Jquery, Angular, Nodejs, Expressjs, MongoDB, Boostrap]
skill_mobile_app_keywords: [Android, Ionic, Cordova]
popular_repos: ['ppt','nodePPT', 'RandomName', 'Java-BackGammon', 'zl810881283.github.io', 'project_template']
contribute_repos: ['academic-zl/SEMAGE', 'outsourcingproject/auction', 'outsourcingproject/zhazha.com', 'outsourcingproject/wechart_shop']
personal_titles: [ 'Zale plans to be a Full Stack developer', 'Zale dreams to be a CTO', 'Zale is now study in Chongqing university', 'Zale loves coding and innovating', 'Zale has girlfriend now, so not available :D', 'Zale is so cool, right?']