title: Zale - ZhangLe's Website
name: Zale
email: 810881283@qq.com
description: Zale's Website
keywords: [Zale, blog, ZhangLe]

skill_software_keywords: [Java, C, C++, MySQL, Oracle, SQLite, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, JSP]
skill_web_keywords: [HTML, CSS, Javascript, Jquery, Angular, Nodejs, Expressjs, MongoDB, Boostrap]
skill_mobile_app_keywords: [Android, Inoic, Cordova]

timezone: PRC
encoding: "utf-8"

url:
baseurl:  "/"
domain:
permalink:     /articles/:year/:month/:title.html
paginate_path: 'page:num'
paginate:   10
source_code: https://github.com/zl810881283/zl810881283.github.io

# Build settings

exclude: [node_modules]

markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

gems:
  - jemoji
  - rouge
  - jekyll-html-pipeline
  - jekyll-paginate

analytics :
  provider : google
  google :
      tracking_id : 'UA-72165600-1'

# navigation
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /blog
    label: Blog

  -
    href: /footprint
    label: Footprint

  -
    href: /bookmark
    label: Bookmark

  -
    href: /about
    label: About

popular_repos: ['ppt','RandomName', 'Java-BackGammon', 'zl810881283.github.io', 'project_template']
contribute_repos: ['academic-zl/SEMAGE', 'outsourcingproject/auction', 'outsourcingproject/zhazha.com', 'outsourcingproject/wechart_shop']
